// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANVZbI8Qa8oKRqfaVP5x_bdokJ4H7ni1M',
    appId: '1:408467174940:web:bd494863c9763c35da11d9',
    messagingSenderId: '408467174940',
    projectId: 'hackthon-474f6',
    authDomain: 'hackthon-474f6.firebaseapp.com',
    storageBucket: 'hackthon-474f6.appspot.com',
    measurementId: 'G-DNQ58YKZ59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiL3OpADQuLXU1LndEfoI2-8Jk7yOzw9Q',
    appId: '1:408467174940:android:e0d1fe7932e79944da11d9',
    messagingSenderId: '408467174940',
    projectId: 'hackthon-474f6',
    storageBucket: 'hackthon-474f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3fWwW-qjdZ4WG90U1PjG91zUvvy1eoWg',
    appId: '1:408467174940:ios:e88856f691bc8597da11d9',
    messagingSenderId: '408467174940',
    projectId: 'hackthon-474f6',
    storageBucket: 'hackthon-474f6.appspot.com',
    iosClientId: '408467174940-ig44mjnau9l4h5d9nnqvdssv1cfdr4pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackthon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3fWwW-qjdZ4WG90U1PjG91zUvvy1eoWg',
    appId: '1:408467174940:ios:e88856f691bc8597da11d9',
    messagingSenderId: '408467174940',
    projectId: 'hackthon-474f6',
    storageBucket: 'hackthon-474f6.appspot.com',
    iosClientId: '408467174940-ig44mjnau9l4h5d9nnqvdssv1cfdr4pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackthon',
  );
}
